### Mod properties
mod.name="UniLink"
mod.id="unilink"
mod.version="1.0"
mod.description="Allows you to use resources from other directories"

### Publishing
mod.modrinth="Ia6QwDLJ"
mod.curseforge="1474788"
mod.github="unilink"

### Subprojects
["26.1.2"]
pub-end="latest"

["1.21.3"]
pub-end="1.21.11"

["1.20.4"]
pub-start="1.19"
pub-end="1.21.1"

["1.18.2"]
pub-start="1.18"

["1.16.5"]
pub-end="1.21.1"

["1.16.5-forge"]
pub-end="1.16.5"
